# Generated by Django 4.0.2 on 2023-05-31 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='Module Name')),
                ('field', models.CharField(max_length=50, verbose_name='Field Name')),
                ('master_value', models.CharField(max_length=20, verbose_name='Master Value')),
                ('master_key', models.CharField(max_length=50, verbose_name='Master Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
            ],
            options={
                'verbose_name_plural': 'Master',
                'db_table': 'tbl_master',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discription', models.TextField()),
                ('price', models.CharField(max_length=55)),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('seller_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_seller_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product',
                'db_table': 'table_product',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purches_price', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('buyer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_buyer_user', to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell_purchase_app.product')),
                ('seller_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_seller_user', to=settings.AUTH_USER_MODEL)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tracking', to='sell_purchase_app.allmaster')),
            ],
            options={
                'verbose_name_plural': 'Purchase',
                'db_table': 'table_purchase',
            },
        ),
    ]
